[telegram]
token = "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
admins = [1234567]  # the first user in the list will receive a notification when a torrent is completed
workers = 1 # number of python-telegram-bot workers. One worker is more than enough
timeout = 120 # requests timeout in seconds

[qbittorrent]
url = "http://127.0.0.1:8080/"
login = "admin"
secret = "adminadmin"
